name: Add MIT License to All Repositories

on:
  workflow_dispatch:  # Este trigger permite que el flujo de trabajo se ejecute manualmente

jobs:
  add-license:
    runs-on: ubuntu-latest  # Usamos un contenedor de Ubuntu
    env:
      OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }} 
      PATH_LICENSE_SCRIPT: ./scripts/add-mit-license-all-repositories.bash  # Ruta del script que se ejecutará
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Configure Git user
        run: |
          git config --global user.name "Cartago - Automatic Workflow"
          git config --global user.email "cv2mario@gmail.com"

      - name: Run script to add MIT License to all repos
        run: |
          chmod +x ${PATH_LICENSE_SCRIPT}  # Da permisos de ejecución al script
          ${PATH_LICENSE_SCRIPT}  # Ejecuta el script